### ISSUE TITLE
python 2.7 version limit for pyrsistent and other packages

### ISSUE THREAD

**Issue by petschki** [collective/collective.exportimport#110]
`jsonschema` requries `pyrsistent>=0.14.0` which has to be limited to the latest py2.7 compatible version `0.15.7` when installing on python 2

**Comment by fredvd** [comment]
'extending' this issue for other package version issues I ran into when installing collective.exportimport 'main' branch april 2022  into a Plone 4.3.20 site. Below is the list I had to add to the versions to have everything pinned. 

@pbauer  How shall/can we proceed with this, try to capture the requirements and pin things down so they still work with Python2.7/Plone 4.3, should we provide a list in the readme / separate doc file ?  

I am surprised the tests still passed for Plone 4.3  on april 18th,  but in the output you can see that quite a few versions are unpinned in the test run:

https://github.com/collective/collective.exportimport/runs/6059604475?check_suite_focus=true



```
collective.exportimport = 1.5.0.dev0+zest1 (april 22th main branch)
pyrsistent = 0.15.7
PyJWT = 1.7.1
attrs = 21.4.0
beautifulsoup4 = 4.9.3
jsonschema = 3.2.0
plone.rest = 1.6.2
plone.restapi = 7.7.0
plone.schema = 1.3.0
soupsieve = 1.9.6
functools32 = 3.2.3.post2
hurry.filesize = 0.9
ijson = 3.1.4
pathlib2 = 2.3.7.post1
scandir = 1.10.0
typing = 3.10.0.0
```

**Comment by petschki** [comment]
Instead of pinning the versions in `base.cfg` https://github.com/collective/collective.exportimport/blob/5aaab5ef719907f9d550270404566a6711466d42/base.cfg#L41-L55 which does the trick for tests, I'd recomment to use the requirement specifiers https://pip.pypa.io/en/stable/cli/pip_install/#requirement-specifiers in `setup.py -> install_requires` ... so installing the package will know about the version requirements.

**Comment by pbauer** [comment]
Since old versions of setuptools do not support that (see #35) I'll add the pinn to setup.py using the current setup.
