### ISSUE TITLE
Exporters in export_others all write to response object (insufficient support for programmatic usage)

### ISSUE THREAD

**Issue by zopyx** [collective/collective.exportimport#115]
The exporters in export_others all write their JSON data to the `response` object.  This is insufficient for programmatic usage since I want either the JSON data as a result from calling the view or being directly written to the file system as it is done for the individual content-types.

@pbauer 

As a workaround, I would add a parameter `write_to=filename`  as an optional parameter to the `__call__()` implementation that would write the JSON to the given `filename` rather than returning it through the `response` object. Would this be a reasonable contribution, or would you recommend a different way?

**Comment by zopyx** [comment]
My changes are here:

https://github.com/collective/collective.exportimport/tree/ajung-export-others-as-files

I will test the stuff over the next time as part of an upcoming migration.

**Comment by pbauer** [comment]
I usually do something like this:

```python
    export_name = "export_localroles"
    view = api.content.get_view(export_name, portal, request)
    data = view.all_localroles()
    filepath = os.path.join(getConfiguration().clienthome, "{}.json".format(export_name))
    with open(filepath, "w") as f:
        json.dump(data, f, indent=4)
```

But I like the idea to have it there ootb. A pull-request for that would be welcome.
