### ISSUE TITLE
plone.app.multilingual installation detection code fails in Plone 4 and p.a.m 12.x

### ISSUE THREAD

**Issue by erral** [collective/collective.exportimport#144]
The plone.app.multilingual detection code in `import_others` checks that [ITranslationManager](https://github.com/collective/collective.exportimport/blob/main/src/collective/exportimport/import_other.py#L50) interface exists, which is not true for p.a.multilingual 1.2.x.

So when trying to use collective.exportimport in Plone 4 with p.a.multilingual 1.2.x, starting the instance fails because it tries to register the `import_translations` view https://github.com/collective/collective.exportimport/blob/main/src/collective/exportimport/configure.zcml#L163-L169

The point is that the `zcm:condition="installed plone.app.multilingual"` is true but there is no `ImportTranslations` view in the `import_others` file because `HAS_PAM` is false there.

**Comment by pbauer** [comment]
Doesn't Plone 4.3 can run with p.a.m. 2.x? Anyway feel free to change the logic her :)
Also the `if HAS_PAM:` should probably got into the call-method to display a message that pam is not installed. Currently it probably causes a exception.

**Comment by erral** [comment]
Yes, Plone 4.3 can run with p.a.m, but also with 1.2.x and that's the case in our client's site.

Anyway, I am testing to modify the zcml condition to include the ITranslationManager, because I think that's what you want when importing the content. Anyway we shouldn't bother on importing the content into Plone 4.3, so if that zcml condition it would be good to go.
