### ISSUE TITLE
Volto site: create Documents instead of Folders

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.exportimport#162]
When you import content and the parent folder is not there yet, exportimport tries to create a Folder.  This fails on a Volto site:

```
InvalidParameterError: http://localhost:8080/Plone/@@import_content
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module collective.exportimport.import_content, line 176, in __call__
  Module collective.exportimport.import_content, line 236, in do_import
  Module collective.exportimport.import_content, line 319, in import_new_content
  Module collective.exportimport.import_content, line 806, in handle_container
  Module collective.exportimport.import_content, line 876, in get_parent_as_container
  Module collective.exportimport.import_content, line 900, in create_container
  Module decorator, line 232, in fun
  Module plone.api.validation, line 73, in wrapped
  Module decorator, line 232, in fun
  Module plone.api.validation, line 149, in wrapped
  Module plone.api.content, line 80, in create
plone.api.exc.InvalidParameterError: Cannot add a 'Folder' object to the container.
```

Use case: I exported the Plone releases, hotfixes and vulnerabilities from beta.plone.org to test locally, and it failed for this reason.  

I changed `create_container` to create a Document instead, and this worked.
We should probably check if `plone.volto` is installed, and use Document then. Alternatively check if Document is folderish.

(If anyone wants to try this, you need to comment out some plone-org specific import code as well, because it has hooks that only work when importing the content from 5.1.)

**Comment by pbauer** [comment]
As documented here: https://github.com/collective/collective.exportimport#migrate-to-volto I suggest to import Folders (and Collections) first including default pages etc. and then migrate to Volto like we did for plone.org. The code in that example allows Folders and Richtext during the import and removes it afterwards.
