### ISSUE TITLE
Fix html: wrong image variants chosen

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.exportimport#176]
I see possible improvements for the `@@fix_html` page.

- Currently it gets all objects in the site, would be nice if it can work on the context, like most views here.
- The fallback picture variant is `preview`, but by default this does not exist. Default choices are large, medium, small. Medium seems the most logical choice.
- Would be good to be able to override this. I have a site where most of the images are quite small, so small might be a better default there.
- The scale to variant mapping actually seems the wrong way around. I have an image with scale 'large'. The code adds image variant 'larger' for this, but this does not exist: it should be 'large'. When I edit the page, click on the image, and click the icon to edit the image, no image variant is selected.

I am working on a PR.

**Comment by pbauer** [comment]
Thanks!
