### ISSUE TITLE
Discussion importer should not check for discussion support being enabled on a particular content object

### ISSUE THREAD

**Issue by zopyx** [collective/collective.exportimport#182]
The code in 

https://github.com/collective/collective.exportimport/blob/main/src/collective/exportimport/import_other.py#L603-L604

avoids the import of discussions for objects with discussion disabled.

A content may have discussions and may have the discussion support disabled at some point (discussion being open for a particular time). The option to disable a discussion on a content object does not mean that the import should be disallowed the discussion items for historic reasons.

**Comment by zopyx** [comment]
Workaround: removing the two lines of code in our fork

**Comment by pbauer** [comment]
Good point. If you have time please add a PR.

**Comment by zopyx** [comment]
https://github.com/collective/collective.exportimport/pull/188

**Comment by pbauer** [comment]
thanks!
