### ISSUE TITLE
why is the UID set after the custom_contenttype hook? 

### ISSUE THREAD

**Issue by fredvd** [collective/collective.exportimport#185]
for importing RelationValues on persistent tiles I need to get the UID of the item I'm importing to store it in a queue for later processing, after all content has been imported in the finish hook. But in this part od the code below, the UID is set after the custom hook.

Does that have a particular reson?  can we move it above the custom hook calls?

https://github.com/collective/collective.exportimport/blob/1d3f5d31182ec653aed66fd0adff8c6e5011728e/src/collective/exportimport/import_content.py#L427

@pbauer @mauritsvanrees

**Comment by mauritsvanrees** [comment]
Seems okay to move it above.

**Comment by pbauer** [comment]
I agree, it would not hurt to move that up.
