### ISSUE TITLE
Readme does not render due a issue in github

### ISSUE THREAD

**Issue by pbauer** [collective/collective.exportimport#239]
See https://github.com/orgs/community/discussions/86715

I also reported the issue to github support and it was tracked in as https://support.github.com/ticket/2527435 (not publicly accessible).

I finally got this answer:

> The engineering team have identified the (main) cause of what's going on - an update that has been rolled out to the python docutils library used by Ubuntu, which our renderer is reliant on, has changed the libraries behavior. That library had some bugs patched that were previously allowing errors in rst files to fly under the radar. Those errors are now preventing the files from rendering.
>  
> The investigation is still ongoing, but in the immediate term you may be able get the files rendering again by using [rstcheck](https://pypi.org/project/rstcheck/) to identify any errors in your files, and repairing them. Please note, though, I said "(main) cause" above because we have seen some reports of rst files being repaired using the errors identified in rstcheck, but the files are still not rendering. Engineering is continuing to look into this, and we'll get back to you when we have a more definitive update!

The problem is still ongoing even though @stevepiercy fixed issues found by `rstcheck`.

**Comment by stevepiercy** [comment]
See also:

- https://github.com/plone/documentation/issues/1612
- https://github.com/plone/documentation/pull/1622
- https://github.com/orgs/community/discussions/86715

We have a temporary workaround, extending the response timeout to 10 seconds, but that is not a good solution.

**Comment by pbauer** [comment]
This is now fixed by github

**Comment by stevepiercy** [comment]
No, I need to revoke the workaround I put in place in the repo, then it can be closed. We also need to verify that the affected READMEs do, in fact, render properly, as there are continued reports of things such as code blocks not rendering correctly.

**Comment by stevepiercy** [comment]
Nope, it's broken. See code examples in both:

- https://github.com/collective/collective.exportimport?tab=readme-ov-file#export-example
- https://github.com/zopefoundation/z3c.form/tree/master/src/z3c/form/browser#browser-support

I'm monitoring the thread. @pbauer can you update your ticket to reference the initial report in [GitHub Community](https://github.com/orgs/community/discussions/86715)?

**Comment by pbauer** [comment]
They already archived my ticket. I think monitoring https://github.com/orgs/community/discussions/86715 is good enough for now.

**Comment by stevepiercy** [comment]
The first link works now, the second does not render pycon correctly. Still monitoring in https://github.com/orgs/community/discussions/86715#discussioncomment-9159996

**Comment by stevepiercy** [comment]
GitHub fixed a few more things, and now the second link renders OK as well. https://github.com/orgs/community/discussions/86715#discussioncomment-9705928

I need to revert my earlier workaround, then I will close this issue.
