### ISSUE TITLE
ATField (without base64 data) -> DXField: data missing

### ISSUE THREAD

**Issue by petschki** [collective/collective.exportimport#26]
Somehow I do not get the trick. If I export my ATFileAttachment without base64 data it looks like this:

<img width="733" alt="Bildschirmfoto 2021-05-27 um 09 25 15" src="https://user-images.githubusercontent.com/511761/119783586-a3c37180-becd-11eb-9fb6-83f40a4ed8fb.png">

Now importing this with a custom_dict_hook ("ATFileAttachment" -> "DXFile") creates a File object as expected, but the `file` field has not data 😢 ... so if I'm correct, the plone.restapi deserializer doesn't load data from remote origins? do I have to take care about this myself?

@pbauer @fredvd can anyone give me a hint on this?

**Comment by pbauer** [comment]
Yes, importing files without the data (e.g. as base64) is not supported yet.  
I had good results with base64 data even for large sites. I have not tried the very large one though. See https://github.com/collective/collective.exportimport/issues/17

For the very large site (>80GB) I so far export the blob-path:

```
@adapter(IBlobField, IBaseObject, IContentexportLayer)
@implementer(IFieldSerializer)
class CustomATFileFieldSerializerWithBlobs(ATDefaultFieldSerializer):
    def __call__(self):
        file_obj = self.field.get(self.context)
        if not file_obj:
            return None
        oid = file_obj._p_oid
        tid = file_obj._p_serial
        fshelper = file_obj._p_jar._storage.fshelper
        blobfilepath = fshelper.layout.getBlobFilePath(oid, tid)
        result = {
            "filename": self.field.getFilename(self.context),
            "content-type": self.field.getContentType(self.context),
            "blob_path": blobfilepath,
        }
        return json_compatible(result)
```

```
  <adapter zcml:condition="installed plone.app.blob"
      factory=".serializer.BrainATFileFieldSerializerWithBlobs" />
```

I've not yet gotten to the import since I'm busy with other tasks.
