### ISSUE TITLE
original creation date lost when migrating from AT to DX

### ISSUE THREAD

**Issue by petschki** [collective/collective.exportimport#29]
since `creation_date` is moved to `created` when you activate data migration, the original creation date is not set ... leaving it on `creation_date` works also for DX...

https://github.com/collective/collective.exportimport/blob/main/src/collective/exportimport/export_content.py#L302

**Comment by fredvd** [comment]
@petschki I'll test this today when I do a new test migration needing AT-DX data migration.  I can confirm that in my previous migration target site the creation dates are now wrong and all set to the import date/time. 

I would expect that if creation_date shouldn't be touched the same should go for modification_date. But for modification_date there is an extra step in the import_content control panel to fetch the modification_date from an extra attribute and re-apply.

**Comment by fredvd** [comment]
@petschki @pbauer   Both with and without

>  item = migrate_field(item, 'creation_date', 'created')

in my export_content method, when I import for example folders in Plone 5.2 from a Plone 4 site, the creation date is not picked up and set to import time. I get the impression the plone.restapi deserializer is not capable of handling this correctly and we need to do something similar for creation date as what Philip has made for modification date. Set an extra attribute/copy of modifiied on the target object and run a separate method later to set the Creation Date as well.

I'm curious as to why you both seem to have mixed/better results here. The only variation I can come up with right now is
using diferent versions of plone.restapi where the deserializer unpacks creation_date/created correctly.  I'm now using plone.restapi 7.0 as pinned by plone-versions.cfg for 5.2.4.

**Comment by petschki** [comment]
You're right ... that's why I made something like this in my `CustomImportView`:
```
    def global_obj_hook(self, obj, item):
        # set creation date
        obj.creation_date = item.get("created", item.get("creation_date"))
        return obj
```

but it would be sure a better solution to solve this the same as modification dates ...

**Comment by fredvd** [comment]
I've temporarily fixed this by duplicating the modification_date handling for creation_date.  So an extra attribute is set and restored in the ResetModificationDate view.
