### ISSUE TITLE
feature: also support upload from server, large import .json's crash the server/browser

### ISSUE THREAD

**Issue by fredvd** [collective/collective.exportimport#3]
@pbauer added download to server for eported .json files. I think we'll also need add 'import from server'.  I've successfully export 5+ Gb of File Items into a File.json, but cannot import these back into a fresh Plone site because either the browser or the local Plone server crashes/aborts when uploading this through the frontend :-(

**Comment by pbauer** [comment]
How about using the same approach as the old ZMI export/import? All json-files in var/instance/import could be offered.

**Comment by fredvd** [comment]
Yes, that's the code I'd want to study and if possible re-use to get the bytes from local FS. :-)

**Comment by pbauer** [comment]
A problem with 5GBb export/import will be memory since the code currently deserialized the while json file into a list of dicts, which will probably use at least 2x5GB. Maybe https://pypi.org/project/ijson can be a solution for that.

**Comment by pbauer** [comment]
Also: The files will only be huge if you include blobs. A approach could be to not include the blob-data and deal with re-attaching existing blobs later. See https://community.plone.org/t/flame-alert-the-plone-python-3-upgrade-story/12803/42?u=pbauer

**Comment by pbauer** [comment]
I made a quick test with ijson and that worked like a charm.
When I used `data = ijson.items(jsonfile, 'item')` instead of `data = json.loads(jsonfile.read())` memory-consumption of python stayed down to 250MB even when I imported files larger than 1GB.

**Comment by mauritsvanrees** [comment]
See PR #14.

**Comment by mauritsvanrees** [comment]
Note: upload from server is only supported on the `import_content` page, not on the others, like `import_members`.  But you cannot _save_ the other exports to server either: there is only one button to click, nothing to choose. Aldo, upload from server is less needed for the others, because they are likely small. I do want to support this at some point, but I am not in a hurry. Something for the future.
