### ISSUE TITLE
Event with empty event_url field causes ValidationError in deserialization and "AttributeError: creation_date_migrated"

### ISSUE THREAD

**Issue by fulv** [collective/collective.exportimport#75]
An Event exported from a Plone 4.3.6 site has the `event_url` field being an empty string if the field on the original object was not set.
As a result, when importing this object into a 5.2 site, this WARNING will be logged:

`WARNING [collective.exportimport.import_content:310] cannot deserialize http://localhost:.../...: BadRequest([{'message': 'The specified URI is not valid.', 'field': 'event_url', 'error': 'ValidationError'}],)`

This happens in `ImportContent.import_new_content()`:

            # import using plone.restapi deserializers
            deserializer = getMultiAdapter((new, self.request), IDeserializeFromJson)
            try:
                new = deserializer(validate_all=False, data=item)
            except Exception as error:
                logger.warning(
                    "cannot deserialize {}: {}".format(item["@id"], repr(error))
                )
                continue

One of the bad side-effects of this is that the folowing line is never reached for this object:

https://github.com/collective/collective.exportimport/blob/main/src/collective/exportimport/import_content.py#L356:

                new.creation_date_migrated = creation_date

Therefore, when later running `@@reset_dates`, this Event will produce this error:

`AttributeError: creation_date_migrated`

This is because acquisiton causes `getattr(obj, "creation_date_migrated", None)` to be true-ish, but `del obj.creation_date` raises `AttributeError`:

            created = getattr(obj, "creation_date_migrated", None)
            if created and created != obj.creation_date:
                obj.creation_date = created
                del obj.creation_date_migrated
                obj.reindexObject(idxs=["created"])

All of this can be avoided by setting `item['event_url'] = None`, which is what I did in a custom `global_dict_hook()`:

```
def global_dict_hook(self, item):
    url = item.get('event_url', None)
    if url == '':
        item['event_url'] = None
    return item
```

Utlimately, I'm not sure if this should be addressed in plone.restapi or here, but it's one of various issues (like #12) that affect default content types and should not require custom hooks.

**Comment by pbauer** [comment]
fixed in 3210d4db0a466dc3aa3a4773891c00b0c5e210c1
