### ISSUE TITLE
Feature request: exclude path

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.exportimport#83]
Just as content export has a "start from this path" input field, there should be a "do not recurse in the following paths" field (perhaps a multiline field / list) that makes the content exporter iterator completely skip anything below those paths.  For many use cases, this is not necessary since the exported JSON can be filtered to exclude said content, but there are cases for very large sites where the user would rather not have to wait until everything is exported.

Concomitant to this, perhaps it would not be such a bad idea to allow for exports of multiple roots rather than a single one.  Right now I have four Plone sites in a single Zope instance, and I have to export them all individually rather than at once.  It's a bit of a bummer, frankly (and I also could never get the plone api get view thingie to work in scripts — when I do it that way, no objects are exported).

**Comment by pbauer** [comment]
I don't think that makes sense as a UI feature. In code it is already easy enough to do using the documented variable `DROP_PATHS` in export and imports. 
It would be more rewarding to use the querystring-widget (like for collections) to be able to define a specific subset of content to export. See #63
